version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        ENVIRONMENT_LEVEL: ${ENVIRONMENT_LEVEL}
    container_name: python_app_base
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    devices:
      - /dev/dri
    network_mode: "host"
