version: '3.8'

services:
  app:
    container_name: python_app_dev
    environment:
      - ENV=development
    volumes:
      - .:/workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
