name: Auto Merge Version Sync PRs

on:
  pull_request:
    branches:
      - fix
      - development
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto-Merge
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state open --json number --jq '.[0].number' --label automated)
          if [[ ! -z "$PR_NUMBER" ]]; then
            gh pr merge $PR_NUMBER --auto --squash
          fi
