name: Create PR from main to release

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request to release
        uses: peter-evans/create-pull-request@v6
        with:
          base: release
          branch: main
          title: "Merge main into release"
          body: "Automated PR to merge main into release"
          labels: automated
