name: Tag on Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # PR がマージされたときに実行

permissions:
  contents: write

jobs:
  tag-on-merge:
    if: github.event.pull_request.merged == true  # PR がマージされた場合のみ実行
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read Version File
        id: read_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Create Git Tag
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ env.VERSION }}
          git push https://x-access-token:${PAT_TOKEN}@github.com/Stone5656/RubikCubeApp.git ${{ env.VERSION }}
