name: Create Versioning PR

on:
  push:
    branches:
      - fix
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  create-version-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest version
        id: get_version
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.0.0"
          fi
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          # "vX.Y.Z" → "X.Y.Z" に変換
          clean_tag="${LATEST_TAG#v}"
          IFS='.' read -r -a parts <<< "$clean_tag"
          major="${parts[0]}"
          minor="${parts[1]}"
          patch="${parts[2]}"

          if [[ "${{ github.ref }}" == "refs/heads/fix" ]]; then
            patch=$((patch + 1))
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            minor=$((minor + 1))
            patch=0
          fi

          new_version="v$major.$minor.$patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Version File
        run: echo "${{ env.NEW_VERSION }}" > VERSION

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}  # `PAT_TOKEN` を使用
          base: main
          branch: version-bump/${{ env.NEW_VERSION }}
          title: "Bump version to ${{ env.NEW_VERSION }}"
          body: "Automated version bump to ${{ env.NEW_VERSION }}"
          labels: automated, versioning
          commit-message: "Bump version to ${{ env.NEW_VERSION }}"
