name: Create Versioning PR

on:
  push:
    branches:
      - fix
      - development

permissions:
  contents: write
  pull-requests: write

jobs:
  create-version-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # すべての履歴を取得

      - name: Pull latest changes
        run: |
          git checkout ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest version
        id: get_version
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            latest_tag="v0.0.0"
          fi
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Bump version
        id: bump_version
        run: |
          clean_tag="${LATEST_TAG#v}"
          IFS='.' read -r -a parts <<< "$clean_tag"
          major="${parts[0]}"
          minor="${parts[1]}"
          patch="${parts[2]}"

          if [[ "${{ github.ref }}" == "refs/heads/fix" ]]; then
            patch=$((patch + 1))
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            minor=$((minor + 1))
            patch=0
          fi

          new_version="v$major.$minor.$patch"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Version File
        run: echo "${{ env.NEW_VERSION }}" > VERSION

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add VERSION
          git commit -m "Bump version to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
          git push --force-with-lease https://x-access-token:${PAT_TOKEN}@github.com/Stone5656/RubikCubeApp.git ${{ github.ref_name }}

      - name: Create PR from fix/development to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: main
          branch: ${{ github.ref_name }} # `fix` または `development`
          title: "Merge `${{ github.ref_name }}` into main"
          body: "Automated PR to merge `${{ github.ref_name }}` into main"
          labels: automated, versioning
          commit-message: "Bump version to ${{ env.NEW_VERSION }}"
          branch-suffix: short-commit-hash # 競合防止
          delete-branch: false
